services:
  db:
    image: postgres:17-alpine3.22
    container_name: survivor-db
    environment:
      POSTGRES_PASSWORD: ${BASE_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - survivor-app
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "no"

  initdb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.initdb
    container_name: survivor-initdb
    environment:
      BASE_POSTGRES_PASSWORD: ${BASE_POSTGRES_PASSWORD}
    # profiles:
    #   - setupdb
    depends_on:
      - db
    networks:
      - survivor-app
    volumes:
      - shared-config:/initdb/shared
    restart: "no"

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: survivor-server
    ports:
      - "4242:4242"
    depends_on:
      - db
      - initdb
    networks:
      - survivor-app
    volumes:
      - shared-config:/server/config
    restart: "no"

  client:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.client
    container_name: survivor-client
    ports:
      - "4240:4240"
    networks:
      - survivor-app
    restart: "no"

networks:
  survivor-app:
    driver: bridge

volumes:
  pgdata:
    driver: local
    name: pgdata
  shared-config:
    driver: local
    name: shared-config
