FROM alpine:3.22.1

WORKDIR /initdb

COPY ./api_dumper ./

RUN apk update && apk add libpq-dev python3 py3-pip

RUN python3 -m venv venv && source venv/bin/activate && python3 -m pip install -r requirements.txt

ENTRYPOINT ["source", "venv/bin/activate", "&&", "./"