CREATE TABLE "Accounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "image_path" varchar(255),
  "password" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" timestamp DEFAULT NULL,
  "last_updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Companies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL,
  "name" varchar(255) UNIQUE NOT NULL,
  "legal_status_id" integer,
  "address" text,
  "phone_number" varchar(15),
  "description" text
);

CREATE TABLE "Partners" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "partnership_type_id" integer
);

CREATE TABLE "Startups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "website_url" varchar(300)
);

CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" integer NOT NULL
);

CREATE TABLE "Founders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL
);

CREATE TABLE "StartupsFounders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "startup_id" integer NOT NULL,
  "founder_id" integer NOT NULL
);

CREATE TABLE "Admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL
);

CREATE TABLE "Investors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "legal_status_id" integer,
  "address" text,
  "phone_number" varchar(15),
  "description" text,
  "investment_focus_id" integer,
  "investor_type_id" integer
);

CREATE TABLE "Projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "startup_id" integer NOT NULL,
  "name" varchar(255) UNIQUE NOT NULL,
  "project_status_id" integer,
  "needs" varchar(50),
  "sector_id" integer,
  "maturity" varchar(50)
);

CREATE TABLE "Events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "location" varchar(255),
  "description" text,
  "event_type_id" integer,
  "target_audience_id" integer
);

CREATE TABLE "EventsCategories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "News" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "location" varchar(255),
  "description" text NOT NULL,
  "company_id" integer NOT NULL
);

CREATE TABLE "PartnerTypes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "SocialMedias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(255) NOT NULL,
  "company_id" integer NOT NULL
);

CREATE TABLE "EventDates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" timestamp NOT NULL,
  "event_id" integer NOT NULL
);

CREATE TABLE "InvestorTypes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "InvestmentFocus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "sector_id" integer NOT NULL
);

CREATE TABLE "LegalStatus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "Sectors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "TargetAudiences" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "ProjectStatus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "ValidationErrors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unformatted_message" text NOT NULL,
  "type" varchar(255) UNIQUE NOT NULL
);

ALTER TABLE "Events" ADD FOREIGN KEY ("target_audience_id") REFERENCES "TargetAudiences" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("account_id") REFERENCES "Accounts" ("id");

ALTER TABLE "Companies" ADD FOREIGN KEY ("account_id") REFERENCES "Accounts" ("id");

ALTER TABLE "Companies" ADD FOREIGN KEY ("legal_status_id") REFERENCES "LegalStatus" ("id");

ALTER TABLE "Founders" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "StartupsFounders" ADD FOREIGN KEY ("startup_id") REFERENCES "Startups" ("id");
ALTER TABLE "StartupsFounders" ADD FOREIGN KEY ("founder_id") REFERENCES "Founders" ("id");

ALTER TABLE "Admins" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Investors" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Investors" ADD FOREIGN KEY ("investment_focus_id") REFERENCES "InvestmentFocus" ("id");

ALTER TABLE "Investors" ADD FOREIGN KEY ("investor_type_id") REFERENCES "InvestorTypes" ("id");

ALTER TABLE "Investors" ADD FOREIGN KEY ("legal_status_id") REFERENCES "LegalStatus" ("id");

ALTER TABLE "InvestmentFocus" ADD FOREIGN KEY ("sector_id") REFERENCES "Sectors" ("id");

ALTER TABLE "Startups" ADD FOREIGN KEY ("company_id") REFERENCES "Companies" ("id");

ALTER TABLE "Partners" ADD FOREIGN KEY ("partnership_type_id") REFERENCES "PartnerTypes" ("id");

ALTER TABLE "Partners" ADD FOREIGN KEY ("company_id") REFERENCES "Companies" ("id");

ALTER TABLE "Projects" ADD FOREIGN KEY ("sector_id") REFERENCES "Sectors" ("id");

ALTER TABLE "Projects" ADD FOREIGN KEY ("startup_id") REFERENCES "Startups" ("id");

ALTER TABLE "Projects" ADD FOREIGN KEY ("project_status_id") REFERENCES "ProjectStatus" ("id");

ALTER TABLE "SocialMedias" ADD FOREIGN KEY ("company_id") REFERENCES "Companies" ("id");

ALTER TABLE "News" ADD FOREIGN KEY ("company_id") REFERENCES "Companies" ("id");

ALTER TABLE "EventDates" ADD FOREIGN KEY ("event_id") REFERENCES "Events" ("id");

ALTER TABLE "Events" ADD FOREIGN KEY ("event_type_id") REFERENCES "EventsCategories" ("id");
